server:
    port: 8700

spring:
#  application:
#    name: smart_ruler
#  profiles:
#    active: prod

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT?characterEncoding=UTF-8   #jdbc:mysql://localhost:3306/dbgirl_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: root
      password: root
      cachePrepStmts: true  # 开启二级缓存

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  type-aliases-package: org.spring.springboot.domain

account:
  host: account
  port: 8400
  check_url: http://account:8400/api/v1/account/check_token
  login_url: http://account:8400/api/v1/account/login
  client_id: client_2
  client_secret: 123456
  internal_client_id: client_1
  internal_client_secret: 123456
